spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://server1jvs.postgres.database.azure.com:5432
    username: bdvelandiap@server1jvs
    password: Root123456789

  jpa:
    database: POSTGRESQL
    show-sql: false
server:
  port: 8080
